
vpath %.c Src

# Includes
INCLUDES  = -ISTM32F7xx_HAL_Driver/Inc/ -I../Inc/ -ICMSIS/Device/ST/STM32F7xx/Include/ -ICMSIS/Include/
INCLUDES += -IUSB_Device/Core/Inc -IUSB_Device/Class/CDC/Inc

# Sources
SRCS  = STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c
SRCS += STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c

SRCS += STM32F7xx_HAL_Driver/Src/tm_stm32_buffer.c
SRCS += STM32F7xx_HAL_Driver/Src/tm_stm32_gpio.c
SRCS += STM32F7xx_HAL_Driver/Src/tm_stm32_usb_device.c
SRCS += STM32F7xx_HAL_Driver/Src/tm_stm32_usb.c
SRCS += STM32F7xx_HAL_Driver/Src/tm_stm32_usb_device_cdc.c

SRCS += USB_Device/Core/Src/usbd_conf.c
SRCS += USB_Device/Core/Src/usbd_core.c
SRCS += USB_Device/Core/Src/usbd_ctlreq.c
SRCS += USB_Device/Core/Src/usbd_ioreq.c
SRCS += USB_Device/Class/CDC/Src/usbd_cdc.c
SRCS += USB_Device/Class/CDC/Src/usbd_cdc_if.c

LOCAL_FLAGS += -DUSB_USE_FS -DUSB_USE_HS -DUSB_USE_DEVICE

ifeq ($(ENABLE_USB_VCP),)
	LOCAL_FLAGS += -DUSB_USE_FS -DUSB_USE_HS -DUSB_USE_DEVICE
endif

OBJS = $(SRCS:.c=.o)
LIBNAME = libstdperiph.a

all: $(LIBNAME)

%.o : %.c
	$(CC) $(CFLAGS) $(LOCAL_FLAGS) $(INCLUDES) -c -o $@ $^

$(LIBNAME): $(OBJS)
	$(AR) -r $(OUTPUT_PATH)/$@ $(OBJS)

clean:
	rm -f $(OBJS) $(LIBNAME)
